_BASE_: "mobilenet_small_1x.yaml"
MODEL:
  WEIGHTS: "./output/fsod/mobilenet_small_1x/model_final.pth" 
  MASK_ON: False
  BACKBONE:
    FREEZE_AT: 5
DATASETS:
  TRAIN: ("coco_2017_train_stone",)
  TEST: ("coco_2017_val_stone",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
  STEPS:  (2000, 3000) #(2000,3000)
  MAX_ITER:  3100  # 3100
  WARMUP_ITERS: 200
INPUT:
  FS:
    FEW_SHOT: False # True #False,fine-tune
    SUPPORT_WAY: 2
    SUPPORT_SHOT: 9
  MIN_SIZE_TRAIN: (240, 272, 304, 336, 368, 400) #(440, 472, 504, 536, 568, 600)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 370 # 620 # 370
  MAX_SIZE_TEST: 1000 
OUTPUT_DIR: './output/fsod/finetune_dir/mobilenet_small_1x'

