# _BASE_: "Base-FSOD-C4.yaml"
# MODEL:
#   WEIGHTS: "https://download.pytorch.org/models/mobilenet_v3_small-047dcff4.pth"
#   MASK_ON: False
#   BACKBONE:
#     NAME: "build_mobilenetV3small_backbone"
# OUTPUT_DIR: './output/fsod/mobilenet_small_1x'


MODEL:
  META_ARCHITECTURE: "FsodRCNN"
  PROPOSAL_GENERATOR:
    NAME: "FsodRPN"  
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 100
  ROI_HEADS:
    NAME: "FsodRes5ROIHeads"
    BATCH_SIZE_PER_IMAGE:  128
    POSITIVE_FRACTION: 0.5
    NUM_CLASSES: 1
  #WEIGHTS: "https://download.pytorch.org/models/mobilenet_v3_small-047dcff4.pth" #/home/lcheng/FewX-master/FewX-master/tool/m_s.pkl #"https://download.pytorch.org/models/mobilenet_v3_small-047dcff4.pth"
  MASK_ON: False
  BACKBONE:
    NAME: "build_mobilenetV3small_backbone"
  #  FREEZE_AT: 2
  #PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
DATASETS:
  TRAIN:  ("coco_2017_train_nonvoc",) #("coco_2017_train_nonvoc",) #("coco_2017_train",)
  TEST: ("coco_2017_val",) # ("coco_2017_val",)
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  IMS_PER_BATCH: 8 #16
  BASE_LR: 0.0002 #0.02 #0.0005
  STEPS: (100000, 120000) #(100000, 10000) #(30000, 40000) #(56000,) #(60000, 80000)
  MAX_ITER: 121000 #300000 #45000 #60000 #90000
  WARMUP_ITERS: 500 # 1000 # 500
  WARMUP_FACTOR: 0.1
  CHECKPOINT_PERIOD: 30000 # 30000
  HEAD_LR_FACTOR: 2.0 # 2.0
  #WEIGHT_DECAY_BIAS: 0.0 # WEIGHT_DECAY_BIAS: 0.0
INPUT:
  FS:
    SUPPORT_WAY: 2
    SUPPORT_SHOT: 10
  MIN_SIZE_TRAIN:  (440, 472, 504, 536, 568, 600) # (440, 472, 504, 536, 568, 600) #(600,) #(640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
OUTPUT_DIR: './output/fsod/mobilenet_small_1x'
VERSION: 2
