_BASE_: "Base-FSOD-C4.yaml"
MODEL:
  WEIGHTS:  /home/lcheng/FewX-master/FewX-master/tool/r18.pkl #"detectron2://ImageNetPretrained/MSRA/R-.pkl"
  MASK_ON: False
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  RESNETS:
    DEPTH: 18
    STRIDE_IN_1X1: False
OUTPUT_DIR: './output/fsod/R_18_C4_1x_2.0'
